// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/liliksetyawan/orderflow/services/inventory/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// GetByOrderID mocks base method.
func (m *MockReservationRepository) GetByOrderID(ctx context.Context, orderID string) (*domain.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderID", ctx, orderID)
	ret0, _ := ret[0].(*domain.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderID indicates an expected call of GetByOrderID.
func (mr *MockReservationRepositoryMockRecorder) GetByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderID", reflect.TypeOf((*MockReservationRepository)(nil).GetByOrderID), ctx, orderID)
}

// RecordFailed mocks base method.
func (m *MockReservationRepository) RecordFailed(ctx context.Context, r *domain.Reservation, ev []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailed", ctx, r, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFailed indicates an expected call of RecordFailed.
func (mr *MockReservationRepositoryMockRecorder) RecordFailed(ctx, r, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailed", reflect.TypeOf((*MockReservationRepository)(nil).RecordFailed), ctx, r, ev)
}

// ReleaseAtomic mocks base method.
func (m *MockReservationRepository) ReleaseAtomic(ctx context.Context, r *domain.Reservation, ev []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseAtomic", ctx, r, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseAtomic indicates an expected call of ReleaseAtomic.
func (mr *MockReservationRepositoryMockRecorder) ReleaseAtomic(ctx, r, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAtomic", reflect.TypeOf((*MockReservationRepository)(nil).ReleaseAtomic), ctx, r, ev)
}

// ReserveAtomic mocks base method.
func (m *MockReservationRepository) ReserveAtomic(ctx context.Context, r *domain.Reservation, ev []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveAtomic", ctx, r, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveAtomic indicates an expected call of ReserveAtomic.
func (mr *MockReservationRepositoryMockRecorder) ReserveAtomic(ctx, r, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveAtomic", reflect.TypeOf((*MockReservationRepository)(nil).ReserveAtomic), ctx, r, ev)
}
