// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source=gateway.go -destination=mocks/gateway_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentGateway is a mock of PaymentGateway interface.
type MockPaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayMockRecorder
	isgomock struct{}
}

// MockPaymentGatewayMockRecorder is the mock recorder for MockPaymentGateway.
type MockPaymentGatewayMockRecorder struct {
	mock *MockPaymentGateway
}

// NewMockPaymentGateway creates a new mock instance.
func NewMockPaymentGateway(ctrl *gomock.Controller) *MockPaymentGateway {
	mock := &MockPaymentGateway{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGateway) EXPECT() *MockPaymentGatewayMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentGateway) Charge(ctx context.Context, orderID, customerID string, amount int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, orderID, customerID, amount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentGatewayMockRecorder) Charge(ctx, orderID, customerID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentGateway)(nil).Charge), ctx, orderID, customerID, amount)
}

// Refund mocks base method.
func (m *MockPaymentGateway) Refund(ctx context.Context, providerRef string, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, providerRef, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockPaymentGatewayMockRecorder) Refund(ctx, providerRef, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPaymentGateway)(nil).Refund), ctx, providerRef, amount)
}
